[{"name": "test.test_find_matching.FindMatching.test_calls", "status": "failed", "message": "Expected 'enumerate' to have been called once. Called 0 times.", "passed": false, "points": ["p01-14.1"], "backtrace": ["  File \"/usr/lib/python3.12/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/marco/python-data-analysis-helsinki/01-python/mooc-data-analysis-with-python-2024-2025/part01-e14_find_matching/test/test_find_matching.py\", line 25, in test_calls\n    p.assert_called_once()\n", "  File \"/usr/lib/python3.12/unittest/mock.py\", line 923, in assert_called_once\n    raise AssertionError(msg)\n"]}, {"name": "test.test_find_matching.FindMatching.test_empty", "status": "passed", "message": "", "passed": true, "points": ["p01-14.1"], "backtrace": []}, {"name": "test.test_find_matching.FindMatching.test_first", "status": "failed", "message": "Lists differ: [] != [0, 1, 3]\n\nSecond list contains 3 additional elements.\nFirst extra element 0:\n0\n\n- []\n+ [0, 1, 3]", "passed": false, "points": ["p01-14.1"], "backtrace": ["  File \"/usr/lib/python3.12/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/marco/python-data-analysis-helsinki/01-python/mooc-data-analysis-with-python-2024-2025/part01-e14_find_matching/test/test_find_matching.py\", line 20, in test_first\n    self.assertEqual(result, [0,1,3])\n"]}]